### PR TITLE
Math-Magicians React App Setup

### PR DESCRIPTION
**Pull request by Fatima-hub333**
<h1> Math Magicians Website Setup </h1>

The following changes were implemented in this Milestone : [Math magicians: setup](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/project_setup.md): 

- [ ]  Create Setup for Math magicians React App by using CRA (Create React App) guide instructions.

<h3> Thanks for taking out the time to review this project 🧨 </h3>
It really is appreciated :) ❤️ 

- Note: I personally love optional suggestions so please do leave some 😄

### CODE REVIEW

**Comment by Kingstalux** [comment]
Hello @Fatima-hub333,
Could you remove all the files and folders in the `my-app` folder and place them in the root directory? Especially the `.github` folder. It should be in the root directory so that the linters checks can run.

**Review by Kingstalux — COMMENTED** [review]
Hi @Fatima-hub333, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ 

- [ ] You have submitted a project, that does not have linters checks. Kindly fix your Github action and make sure your linter checks are showing and they should be passing 👍 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Fatima-hub333** [comment]
Hi, Thank you for your help. can you text me on slack? I need your help.

**Review by gemmen29 — APPROVED** [review]
Hi @Fatima-hub333, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 



## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
